---
name: Catalyst-Plugin-Session-Store-DBI
version: 0.10
author:
  - 'Andy Grundman, <andy@hybridized.org>'
abstract: Store your sessions in a database
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.49
  Catalyst::Plugin::Session: 0.05
  DBI: 0
  MIME::Base64: 0
  Storable: 0
provides:
  Catalyst::Plugin::Session::Store::DBI:
    file: lib/Catalyst/Plugin/Session/Store/DBI.pm
    version: 0.10
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
